# Generated by Django 5.0.2 on 2024-02-25 01:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="todo",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="todo",
            name="title",
            field=models.CharField(default="testing title", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="todo",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
